### PR TITLE
closes #65 RS typo in RSCAT

### LINKED ISSUE #65: RS typo in RSCAT
RECISIT 1.1 -> RECIST 1.1

@Gopi2345 would you have time to fix this minor one i spotted? no rush with timing and let me know if any issue

### PR DESCRIPTION
**Pull request by Gopi2345**

### CODE REVIEW

**Comment by Gopi2345** [comment]
Hi Ben,
Seems the folder structure in DEVEL is changed when compared to this RSTYPO.  In the updated folder structure, the program is in DEVEL/DEV, where as in my RSTYPO branch it is in INST/DATA_SCRIPTS.  To resolve the merge conflicts, seems  I need to close this RSTYPO branch and freshly create a branch a from DEVEL and then fix the RS typo. Can I do like that or any other suggestion?

Regards,
Gopi Vegesna

**Comment by rossfarrugia** [comment]
@thomas-neitmann please can you take a look and advise Gopi?

**Comment by bms63** [comment]
Apologies did this get resolved?

**Comment by Gopi2345** [comment]
Hi Ben, No. The folder structure in DEVEL is changed . So RSTYPO is not merging. Not sure how to proceed.

Regards,
Gopi
________________________________

**Comment by bms63** [comment]
Hi Gopi,

I think the easiest way is to pull out the code you updated to fix the typo.   NExt close this PR and start a new one off of `devel`.  Then put your code into the proper place so the update goes through in the `dev/rs.R` .

The `dev` folder is all the code we use to update and modify the sdtm datasets.  However, we want to keep this package light and data-focused and dependencies-free.  This is why we moved the code to the `dev` folder and use the `.Rbuildignore` to ignore the `dev` folder when building the package.

Many thanks for seeing this through!!

**Comment by Gopi2345** [comment]
Closing this pull request and start a new pull request as merge conflicts are difficult to resolve.

**Comment by Gopi2345** [comment]
Hi Ben,

Old pull request is cancelled, and new request is created. Hope this will resolve merge conflict.

Regards,
Gopi
________________________________

**Comment by rossfarrugia** [comment]
@Gopi2345 this one was already fixed and merged: https://github.com/pharmaverse/admiral.test/pull/72

**Pull request closed without merging**
