### PR TITLE
Updated labels using metatools package

### PR DESCRIPTION
**Pull request by SyedMubasheer**
Thank you for your Pull Request! 

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. 

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by bms63 — COMMENTED** [review]
It looks like `admiral_supptr` and `admiral_tu` are almost fully removed??  Is everything still there?  
image

**Comment by bms63** [comment]
Also can you resolve the conflicts please.

**Comment by SyedMubasheer** [comment]
> Also can you resolve the conflicts please.

Sure Ben!

**Comment by bms63** [comment]
@SyedMubasheer Is the data the same?  I'm concerned these are not the same datasets as there is so many deletions in that screenshot.

**Comment by bms63** [comment]
FYI @bundfussr Using metatools across the dev scripts just to be consistent.

**Review by bms63 — APPROVED** [review]

**Pull request merged**
