### PR TITLE
Closes #103 103 update_tr: update TR, TU, and RS

### LINKED ISSUE #103: Update TU, TR, and RS for ADTR vignette
TU, TR, and RS should be updated to add more interesting cases for ADTR. For example:
- "LPERP" and "LDIAM" should be added.
- The location "LYMHP NODE" should be added in TU, to get some nodal lesions.
- Add unscheduled visits or repeated measurements.
- Add assessments which are incomplete but indicate PD.

### PR DESCRIPTION
**Pull request by bundfussr**
Thank you for your Pull Request! 

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. 

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
Did the ungroup for `admiral_tr` get completed here?  #98

**Comment by bundfussr** [comment]
@bms63 , yes, this should be fixed here.

**Comment by fshanlee** [comment]
@bundfussr , please could you resolve the merge conflicts?

**Review by fshanlee — COMMENTED** [review]
Hi @bundfussr , I'm assuming that after you updated the code, you ran tr.R, then subsequently re-ran rs.R and tu.R: is that correct? 
The code looks good to me, but I have no experience of oncology data, so I would prefer that someone who is familiar with oncology data actually approves this pull request.

**Comment by bms63** [comment]
> Hi @bundfussr , I'm assuming that after you updated the code, you ran tr.R, then subsequently re-ran rs.R and tu.R: is that correct? The code looks good to me, but I have no experience of oncology data, so I would prefer that someone who is familiar with oncology data actually approves this pull request.

Hey @fshanlee You can use this as a guide for updating the instructions for #106

**Comment by bms63** [comment]
@bundfussr I was told only the labels changed, but it might be prudent to make sure data is still the same.  apologies this conflicted with your PR.

**Comment by bundfussr** [comment]
@fshanlee , I have fixed the conflicts and recreated the datasets.

I would keep the PR open while working on the ADTR vignette. Just in case we need to change something.

**Comment by fshanlee** [comment]
Hi @bundfussr , in lines 7 to 13 of `dev/tu.R`, I think `tr` will be created based on the previous version of `admiral_tr`, not the version that has been created as part of this pull request by running `tr.R`. I tested this by deleting `data/admiral_tr.rda` from my local repo, and the code still ran, whereas if I try to explicitly load `data/admiral_tr.rda`
```

> load("data/admiral_tr.rda")
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/admiral_tr.rda', probable reason 'No such file or directory'

```

**Comment by bundfussr** [comment]
@fshanlee , good point. I have removed the `library(admiral.test)` calls.

**Comment by bms63** [comment]
Hey @bundfussr.  Possible to finalize this today or tomorrow?  Just want to focus on admiral for the remaining week if possible.  Lots of bits and bobs!

**Comment by bundfussr** [comment]
@fshanlee , good idea. I have added a note to the scripts.

**Comment by bms63** [comment]
yes np!!

**Review by HinalPat — APPROVED** [review]

**Review by amitjaingsk — COMMENTED** [review]
@bundfussr  Just trying to understand updates in the TR. I used the admiral.test , 103_update_tr@devel branch to check the data. Hope this is correct.
so, if TRLOC- LYMPH NODE then you used LDIAM, LPERP records. and TRSTRESN for DIAMETER test then in this LYMPH NODE should be the value of TRSTRESN of LPERP. so , manually checked 01-701-1015 subject and TRLOC is in SUPPTR. for T01 is not a lymph node even then TRSTRESN for DIAMETER is value of LPERP. as the SUPP TRLOC T02 lesion is LYMPH NODE. So, just want to make sure. what you are trying to do..

**Comment by bundfussr** [comment]
> @bundfussr Just trying to understand updates in the TR. I used the admiral.test , 103_update_tr@devel branch to check the data. Hope this is correct. so, if TRLOC- LYMPH NODE then you used LDIAM, LPERP records. and TRSTRESN for DIAMETER test then in this LYMPH NODE should be the value of TRSTRESN of LPERP. so , manually checked 01-701-1015 subject and TRLOC is in SUPPTR. for T01 is not a lymph node even then TRSTRESN for DIAMETER is value of LPERP. as the SUPP TRLOC T02 lesion is LYMPH NODE. So, just want to make sure. what you are trying to do..

@amitjaingsk , in the vignette we use `LPERP` for lesions with `TRLOC == "LYMPH NODE"` and `LDIAM` otherwise. In the test data the values for `DIAMETER` are generated randomly first. Then the values for `LPERP` and `LDIAM` are generated by using the `DIAMETER` values and change some of them slightly. I want to achieve that `LPERP` and `LDIAM` are not equal but also not completely different.
By the way, I noticed that I did the modifications the wrong way round. This could result in inconsistencies between PD in RS and PD derived from TR. I have fixed it.

**Comment by bundfussr** [comment]
@HinalPat , I did a small update to avoid inconsistencies between `PD` in `RS` and `PD` derived from `TR`. Could you reapprove?

**Review by HinalPat — APPROVED** [review]

**Comment by bundfussr** [comment]
@bms63 , Hinal has approved this PR but merging is still blocked. I assume she doesn't have write access. Could you give her write access or approve the PR?

**Comment by bms63** [comment]
@HinalPat only has write access.  @bundfussr I gave you admin access so you can merge later on.

**Pull request merged**
