### PR TITLE
Closes 123_Remove `library(admiral.test)` from all programs in `./dev` directory,

### PR DESCRIPTION
**Pull request by fshanlee**
except for tr.R, tu.R and rs.R, as this change has been made in a separate branch for those 3 programs, and I want to avoid merge conflicts when merging into the devel branch.

Thank you for your Pull Request! 

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. 

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by fshanlee** [comment]
Hi @bms63 , I was thinking of re-running all the programs in the `./dev` directory, to confirm that the removal of `library(admiral.test)` does not change any of the datasets in the `./data` directory. However, some of the programs give errors that I don't think are due to the removal of `library(admiral.test)`. For example, `pc.R` crashes when it calls `set_variable_labels()`, but I think that's because it's calling the function incorrectly--please see code and error message at the end of this comment.

Given that the programs in `./dev` do not form part of the built package, **would you be okay with not re-running them for this release?** As far as I know, the existing datasets are fine, so if they need to be re-created in a future release, then any issues with the code in `./dev` could be resolved at that time, and at least we will have already removed potential issues due to calling `library(admiral.test)`.

```
> # add labels
> pc <- pc %>%
+   set_variable_labels(
+     STUDYID = "Study Identifier",
+     DOMAIN = "Domain Abbreviation",
+     USUBJID = "Unique Subject Identifier",
+     PCSEQ = "Sequence Number",
+     PCTESTCD = "Pharmacokinetic Test Short Name",
+     PCTEST = "Pharmacokinetic Test Name",
+     PCORRES = "Result or Finding in Original Units",
+     PCORRESU = "Original Units",
+     PCSTRESC = "Character Result/Finding in Std Format",
+     PCSTRESN = "Numeric Result/Finding in Standard Units",
+     PCSTRESU = "Standard Units",
+     PCNAM = "Vendor Name",
+     PCSPEC = "Specimen Material Type",
+     PCLLOQ = "Lower Limit of Quantitation",
+     VISIT = "Visit Name",
+     VISITNUM = "Visit Number",
+     PCDTC = "Date/Time of Specimen Collection",
+     PCDY = "Actual Study Day of Specimen Collection",
+     PCTPT = "Planned Time Point Name",
+     PCTPTNUM = "Planned Time Point Number"
+   )
Error in set_variable_labels(., STUDYID = "Study Identifier", DOMAIN = "Domain Abbreviation",  : 
  unused arguments (STUDYID = "Study Identifier", DOMAIN = "Domain Abbreviation", USUBJID = "Unique Subject Identifier", PCSEQ = "Sequence Number", PCTESTCD = "Pharmacokinetic Test Short Name", PCTEST = "Pharmacokinetic Test Name", PCORRES = "Result or Finding in Original Units", PCORRESU = "Original Units", PCSTRESC = "Character Result/Finding in Std Format", PCSTRESN = "Numeric Result/Finding in Standard Units", PCSTRESU = "Standard Units", PCNAM = "Vendor Name", PCSPEC = "Specimen Material Type", PCLLOQ = "Lower Limit of Quantitation", VISIT = "Visit Name", VISITNUM = "Visit Number", PCDTC = "Date/Time of Specimen Collection", PCDY = "Actual Study Day of Specimen Collection", PCTPT = "Planned Time Point Name", PCTPTNUM = "Planned Time Point Number")
```

**Comment by bms63** [comment]
We should wait till after release to investigate further.  Can you make an issue please?  

Honestly, I think we might want to set up a CI check to periodically check that all these scripts are working correctly...but still not include in the package.  This way if someone comes to update they aren't fixing broken scripts when they came to just make  a label update or add variable.

**Comment by fshanlee** [comment]
Hi @bms63 , I've created issue #126 .

**Review by bms63 — COMMENTED** [review]
Can you add a little blurb to changelog on removing admiral.test from all the development scripts.

**Comment by fshanlee** [comment]
> Can you add a little blurb to changelog on removing admiral.test from all the development scripts.

@bms63 , I've added a note to NEWS.md.

**Pull request merged**
